version: '3.8'

services:
  # PostgreSQL Database (cháº¡y trong Docker)
  app:
    build: .
    container_name: nestjs-app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nestjs_db
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nestjs-network-local

  postgres:
    image: postgres:16-alpine
    container_name: nestjs-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nestjs_db}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nestjs-network-local

volumes:
  postgres_data_local:
    driver: local

networks:
  nestjs-network-local:
    driver: bridge
